apiVersion: apps/v1
kind: Deployment
metadata:
  name: onfinance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onfinance
  template:
    metadata:
      labels:
        app: onfinance
    spec:
      containers:
        - name: onfinance-container
          image: 971422687529.dkr.ecr.ap-south-1.amazonaws.com/onfinance-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
