apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: onfinance-mysql-db.cdaw0w26oeok.ap-south-1.rds.amazonaws.com       # mysql (encoded) it should be encoded with base64 (echo -n <endpoints> | base64)
  DB_USER: admin       # root it should be encoded with base64 (echo -n <admin> | base64)
  DB_PASS: OnFinance123!   # password it should be encoded with base64 (echo -n <pass> | base64)
